version: "2"
services:
  postgres:
    image: postgres:9.6.4
    restart: always
    networks:
      - default
    volumes:
     - /opt/matrix/pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=Password01
     - POSTGRES_USER=synapse
    labels:
      - "traefik.enable=false"

  synapse:
    image: avhost/docker-matrix:latest
    restart: always
    depends_on:
      - postgres
    networks:
      - web
      - default
    ports:
     # Coturn
     - "3478:3478"
     - "5349:5349"
    volumes:
     - /opt/matrix/synapse/data:/data
    environment:
     - SERVER_NAME=matrix.uevent.online 
     - REPORT_STATS=yes 
    labels:
      - "traefik.backend=synapse"
      - "traefik.enable=true"
      - "traefik.frontend=true"
      - "traefik.port=8008"
      - "traefik.frontend.rule=Host:matrix.uevent.online"
      - "traefik.docker.network=web"
  nginx:
    image: nginx:1.12-alpine
    restart: always
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:matrix.uevent.online"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    volumes:
      - ./nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf
      - ./nginx/www:/var/www/
networks:
  default:
    external:
      name: matrix
  # Traefiks network
  web:
    external: true
